version: 2.0

jobs:
#  "php-7.1":
#    docker:
#      - image: circleci/php:7.1-browsers
#    working_directory: ~/laravel
#    environment:
#      TZ: "/usr/share/zoneinfo/Asia/Taipei"
#    steps:
#      - checkout
#      - restore_cache:
#          keys:
#            - composer-v1-{{ checksum "composer.json" }}
#            - composer-v1-
#      - run: composer install -n --prefer-dist
#      - save_cache:
#          key: composer-v1-{{ checksum "composer.json" }}
#          paths:
#            - vendor
#      - run: ./vendor/bin/phpunit

  "php7.0":
    docker:
      - image: circleci/php:7.0-browsers
    working_directory: ~/laravel
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: ./vendor/bin/phpunit





workflows:
  version: 2
  build:
    jobs:
      - "php70":
          filters:
            branches:
              only:
                - test1
#  "php-7.0":
#  build:
#    jobs:
#      - php70
#        filters:
#          branches:
#            only:
#              - test1